### ISSUE TITLE
Discord link broken in README

### ISSUE THREAD

**Issue by feynon** [Hugobros3/shady#24]
I wanted to join the Discord server for this project, but it seems the [link](https://twitter.com/gobrosse/status/1441323225128968197), which directs to Twitter/X in the readme is broken.

**Comment by Hugobros3** [comment]
I deleted my twitter account. There isn't really a Vcc/Shady discord server, that link if for a general SPIR-V Discord server. I'll think about making one for Vcc if there's interest.

**Comment by Hugobros3** [comment]
Closing this since I got rid of the link in the readme. I'm present on the Vulkan Discord amongst others, you can ask me about Vcc there.

If there is interest for specifically a Vcc Discord server please open another issue, this will likely become a thing once the project is in a state where I can more effectively support end-users.
